testpages:
  image: python:3.6
  tags:
    - primre
  variables:
    AWS_DEFAULT_REGION: us-west-2
    BUCKET_NAME: testcodedocs.primre.org
  script:
  - apt-get update -q -y
  - apt-get install -q -y libblas3 liblapack3 liblapack-dev libblas-dev make git pandoc
  - pip install sphinx awscli
  - git clone https://${MHKIT_PYTHON_USER}:${MHKIT_PYTHON_TOKEN}@code.primre.org/mhkit/mhkit-python.git MHKiT-Python
  - pip install numpy
  - pip install pandas
  - pip install scipy
  - pip install -e MHKiT-Python
  - pip install sphinx_rtd_theme
  - pip install sphinxcontrib-bibtex
  - pip install nbsphinx
  - pip install nbsphinx_link
  - pip install sphinxcontrib-matlabdomain
  - cd docs
  - make html
  - mv _build/html/ public/
  - aws s3 cp public s3://${BUCKET_NAME}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_SLUG} --recursive


pages:
  image: python:3.6
  tags:
    - primre
  variables:
    AWS_DEFAULT_REGION: us-west-2
    BUCKET_NAME: codedocs.primre.org
  script:
  - apt-get update -q -y
  - apt-get install -q -y libblas3 liblapack3 liblapack-dev libblas-dev make git pandoc
  - pip install sphinx awscli
  - git clone https://${MHKIT_PYTHON_USER}:${MHKIT_PYTHON_TOKEN}@code.primre.org/mhkit/mhkit-python.git MHKiT-Python
  - pip install numpy
  - pip install pandas
  - pip install scipy
  - pip install -e MHKiT-Python
  - pip install sphinx_rtd_theme
  - pip install sphinxcontrib-bibtex
  - pip install nbsphinx
  - pip install nbsphinx_link
  - pip install sphinxcontrib-matlabdomain
  - cd docs
  - make html
  - mv _build/html/ public/
  - aws s3 cp public s3://${BUCKET_NAME}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_SLUG} --recursive
  only:
  - master

